### ISSUE TITLE
Some questions about the vgpu device plugin

### ISSUE THREAD

**Issue by Apokleos** [awslabs/aws-virtual-gpu-device-plugin#16]
Hi, @Jeffwan 
I‘’m very interested in the technology, and some questions as below:
1. Are versions prior to V100 supported with the device plugin？
2. Does MPS mode have a single point of failure causing the entire service to crash ？

Thanks a lot!

**Comment by sirajahmed981** [comment]
Hi Jeffwan, 

I am trying to make 4 replicas of a pod access the single GPU on a EKS cluster with a single G4dn.xlarge instance. I see that the pods are able to access GPU concurrently but not parallelly. Does this service work only on P3 instances and not on G4 instance ? I would be grateful if you please clarify this for me.

**Comment by Apokleos** [comment]
> @Apokleos Thanks for eraching out
> 
> 1. Pre-volta do support MPS but not inside container. So this solution is only working in V100 and future versions
> 2. Yes. MPS currently is still not that mature and there're some limitations
> 
> ```
> MPS client processes share on-GPU scheduling and error reporting resources. As a result:
> 
> A GPU exception generated by any client will be reported to all clients, without indicating which client generated the error.
> A fatal GPU exception triggered by one client will terminate the GPU activity of all clients.
> ```
> 
> reference: https://docs.nvidia.com/deploy/mps/index.html#topic_3_3_3_2
> 
> Make sure you totally understand your workload and then this can be used to optimize the cost. If not, please don't use it in production

OK, Got it. Thank you!
