### ISSUE TITLE
Image tag nvidia/cuda:latest deprecated

### ISSUE THREAD

**Issue by nneram** [awslabs/aws-virtual-gpu-device-plugin#25]
In the device plugin daemonset the image `nvidia/cuda:latest` used by `initContainers` is deprecated causing `Init:ImagePullBackOff` for  the pod. 
(See https://hub.docker.com/r/nvidia/cuda)

**Comment by wiertel** [comment]
Wasn't it already reported in #15 ?

**Comment by nneram** [comment]
Yes it is! My bad :) Thanks for pointing it out
