### ISSUE TITLE
Scripts in Enabling virtual GPU Support in Kubernetes part within "Quick Start" can't be downloaded

### ISSUE THREAD

**Issue by phoenixyy** [awslabs/aws-virtual-gpu-device-plugin#6]
The file link in Enabling virtual GPU Support in Kubernetes should be updated to:
https://raw.githubusercontent.com/awslabs/aws-virtual-gpu-device-plugin/master/manifests/device-plugin.yml

The one in the doc right now, can't be downloaded

**Comment by Jeffwan** [comment]
@phoenixyy Thanks for reporting. Let me have a check

**Comment by Jeffwan** [comment]
Fix the readme and resolve the issue
