### ISSUE TITLE
eksctl create nodegroup with p2.xlarge , daemonset start fail  unsatisfied condition: arch >= 7.0

### ISSUE THREAD

**Issue by stevensu1977** [awslabs/aws-virtual-gpu-device-plugin#7]
EKS create by eksctl , eksctl create cluster --node-type=p2.xlarge --name vgpu_workshop

 after I create plugin daemonset I get error message like : 

  Error: failed to start container "mps": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=all --compute --utility --require=arch>=7.0 --pid=32214 /var/lib/docker/overlay2/2da06c58f6f5b50a32a09e4b2a0ff05f71cd564fe05128149b741bcdc80eb43a/merged]\\\\nnvidia-container-cli: requirement error: unsatisfied condition: arch >= 7.0
  
 I'm not sure eksctl default GPU AMI is correct or incorrect for this plugin, default AMI is amazon-eks-gpu-node-1.16-v20200710 (ami-0f027dd81783faa7b).

**Comment by mikestef9** [comment]
Hi @stevensu1977 

See the limitations section https://github.com/awslabs/aws-virtual-gpu-device-plugin#limitations

This plugin only works on P3/G4 or newer GPU instance families

**Comment by stevensu1977** [comment]
@mikestef9  thanks ,   I already install this plugin for P3 instance.
