### ISSUE TITLE
Support more than 10 virtual GPUs for each physical GPU

### ISSUE THREAD

**Issue by walkley** [awslabs/aws-virtual-gpu-device-plugin#8]
Currently each GPU was divided into 10 virtual GPUs which means we cannot assign more than 10 Pods to assign one GPU, I'd like to have some where we can configure the fractional factor to make it support 10+ virtual GPUs.

**Comment by Jeffwan** [comment]
This can be done by adjusting the argument in daemonset. 

https://github.com/awslabs/aws-virtual-gpu-device-plugin/blob/531712799c90f8a6c9f332ff88ba982dce633d0d/main.go#L11

Please help file a PR on manifest to accept a argument if you have time
